# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/pine/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/pine

# Inherit fragments
$(call inherit-product, vendor/xiaomi/pine/pine-vendor-acdb.mk)
$(call inherit-product, vendor/xiaomi/pine/pine-vendor-firmware.mk)

$(call inherit-product-if-exists, vendor/xiaomi/pine-camera/pine-camera-vendor.mk)
